"""crate_table_password_resert

Revision ID: 1e0229a6855c
Revises: 486dbb0ee419
Create Date: 2025-12-06 19:57:10.797799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0229a6855c'
down_revision = '486dbb0ee419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
                    sa.Column('id', sa.String(length=7), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token_hash', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('used', sa.Boolean(), nullable=True),
                    sa.Column('revoked', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('password_reset')
    # ### end Alembic commands ###
