"""add colluns file_path and original_filename

Revision ID: 2db5b8ae1ac0
Revises: 994b6db2d451
Create Date: 2026-01-10 12:08:35.969924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db5b8ae1ac0'
down_revision = '994b6db2d451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_filename',
                            sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
