"""Change IDs, roles and last_login

Revision ID: dfd970676c3c
Revises: 2b2d383aa23b
Create Date: 2025-12-02 02:09:07.869765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd970676c3c'
down_revision = '2b2d383aa23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('role', sa.String(length=20), nullable=False, server_default="user")
        )
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            type_=sa.String(length=7),
            existing_nullable=False
        )

    with op.batch_alter_table('waitingline', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitingline', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
